### ISSUE TITLE
Odd issue when using basic script

### ISSUE THREAD

**Issue by EdwardOak** [qbit/node-pushover#29]
var Push = require( 'pushover-notifications' )
  
var p = new Push( {
  user: process.env['uo9XXXXXXXXXXXXXXXXXXXXXh4g'],
  token: process.env['azj7XXXXXXXXXXXXXXXXXXXXX6iju'],

var msg = {
message: 'omg node test',
}

p.send( msg, function( err, result ) {
  if ( err ) {
    throw err
  }

  console.log( result )
})

This code throws this error:
myapp/pushtest-pushover.js:7
var msg = {
    ^^^

SyntaxError: Unexpected identifier
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by qbit** [comment]
your have a syntax error.
